services:
  - type: web
    name: wheelz-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://wheelz.vercel.app
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
